name: Flutter Release Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  analyze-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: dart analyze --fatal-infos --fatal-warnings
      - run: flutter test

  build-android:
    runs-on: ubuntu-latest
    needs: analyze-test
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build appbundle --release
      - uses: actions/upload-artifact@v4
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/*.aab

  build-ios:
    runs-on: macos-latest
    needs: analyze-test
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: zip -r build/ios/Runner.app.zip build/ios/iphoneos/Runner.app
      - uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/Runner.app.zip
